version: '3'
services:
    api:
        build: .
        expose:
          - "8080"
        ports:
          - "8080:80"
        volumes:
          - .
        links:
          - mongo
    mongo:
      image: mongo
